"use client"
import { useState, useEffect } from "react"
import { supabase } from "@/lib/supabase"
import { useParams } from "next/navigation"
import Link from "next/link"

export default function FlavorCaptions() {
  const { id } = useParams()
  const [flavor, setFlavor] = useState(null)
  const [captions, setCaptions] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => { fetchAll() }, [id])

  async function fetchAll() {
    const { data: flavorData } = await supabase
      .from("humor_flavors")
      .select("*")
      .eq("id", id)
      .single()
    setFlavor(flavorData)

    const { data: requestData } = await supabase
      .from("caption_requests")
      .select("id")
      .eq("humor_flavor_id", id)

    if (requestData && requestData.length > 0) {
      const requestIds = requestData.map(r => r.id)
      const { data: captionData } = await supabase
        .from("captions")
        .select("*")
        .in("caption_request_id", requestIds)
        .order("created_datetime_utc", { ascending: false })
        .limit(100)
      setCaptions(captionData || [])
    }
    setLoading(false)
  }

  if (loading) return (
    <div className="min-h-screen bg-gray-950 flex items-center justify-center">
      <p className="text-white animate-pulse">Loading...</p>
    </div>
  )

  return (
    <main className="min-h-screen bg-gray-950 p-8">
      <Link href={`/flavors/${id}`} className="text-indigo-400 hover:text-indigo-300 mb-6 inline-block">← Back to Steps</Link>
      <h1 className="text-3xl font-black text-white mb-2">💬 Captions for {flavor?.slug}</h1>
      <p className="text-gray-400 mb-8">{captions.length} captions generated by this flavor</p>

      {captions.length > 0 ? (
        <div className="grid grid-cols-1 gap-4">
          {captions.map((c) => (
            <div key={c.id} className="bg-gray-900 border border-gray-700 rounded-2xl p-6">
              <p className="text-white text-lg">{c.content}</p>
              <div className="flex gap-4 mt-3">
                <p className="text-gray-500 text-xs">👍 {c.like_count ?? 0} likes</p>
                <p className="text-gray-500 text-xs">{c.is_featured ? "⭐ Featured" : ""}</p>
                <p className="text-gray-500 text-xs">{new Date(c.created_datetime_utc).toLocaleDateString()}</p>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="bg-gray-900 border border-gray-700 rounded-2xl p-12 text-center">
          <p className="text-5xl mb-4">😶</p>
          <p className="text-gray-400 text-lg">No captions yet for this flavor.</p>
          <Link href={`/flavors/${id}/test`} className="inline-block mt-4 bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded-lg font-semibold transition">
            🧪 Test this flavor to generate some!
          </Link>
        </div>
      )}
    </main>
  )
}